### ISSUE TITLE
老哥本地部署需要注意点啥呀？

### ISSUE THREAD

**Issue by LvXinPeng** [Perye/dokit#2]
clone到本地使用 需要什么组件呢？ 我这边localhost:8080/ 只有你后台打印的一句话

**Comment by LvXinPeng** [comment]
可联系下吗？

**Comment by Perye** [comment]
front是前端页面，需要启动前端项目





**来自GitHub小程序客户端：**

![image](https://user-images.githubusercontent.com/8692455/51429898-b159f400-1c4e-11e9-91a1-59cd1fab5042.png)

**Comment by LvXinPeng** [comment]
> front是前端页面，需要启动前端项目
> 
> **来自GitHub小程序客户端：**
> 
> ![image](https://user-images.githubusercontent.com/8692455/51429898-b159f400-1c4e-11e9-91a1-59cd1fab5042.png)

方便说一下你这项目前端的配置在哪以及怎么启动吗？感谢~

**Comment by Perye** [comment]
你可以先去了解一下vue-cli3的项目，进入front目录，npm install安装依赖，npm run dev启动前端项目
