### ISSUE TITLE
VUE_APP_WS_API 未定义

### ISSUE THREAD

**Issue by akaxiaok** [Perye/dokit#3]
https://github.com/Perye/dokit/blob/4a786a3c0f8a8e4e99b3f4781bce0526219f9a2d/dokit-front/src/views/mnt/deploy/deploy.vue#L149

**Comment by Perye** [comment]
修改 .env.development 文件
ENV = 'development'

# 接口地址
VUE_APP_BASE_API  = 'http://localhost:8080'
VUE_APP_WS_API = 'ws://localhost:8080'

# 是否启用 babel-plugin-dynamic-import-node插件
VUE_CLI_BABEL_TRANSPILE_MODULES = true
