### ISSUE TITLE
点击新增外链菜单怎么不跳出当前页面？ 

### ISSUE THREAD

**Issue by LvXinPeng** [Perye/dokit#5]
点击新增外链菜单怎么不跳出当前页面？~ 只在当前页面的右侧展示呢？这个怎么改呢？谢谢~

**Comment by Perye** [comment]
可参照druid和swagger

**Comment by LvXinPeng** [comment]
方便说的具体要修改哪一块的代码吗？谢谢

**Comment by LvXinPeng** [comment]
> 可参照druid和swagger

方便说的具体下 要修改哪一块的代码吗？拜托了~

**Comment by LvXinPeng** [comment]
> 可参照druid和swagger


<template>
  
  <component v-bind="linkProps(to)">
    <slot />
  </component>
</template>

<script>
import { isExternal } from '@/utils/validate'

export default {
  props: {
    to: {
      type: String,
      required: true
    }
  },
  methods: {
    linkProps(url) {
      if (isExternal(url)) {
        return {
          is: 'a',
          href: url,
          target: '_self',
          rel: 'noopener'
        }
      }
      return {
        is: 'router-link',
        to: url
      }
    }
  }
}
</script>


是这块吧?应该怎么改呢？
